DROP DATABASE IF EXISTS taco_db;
CREATE DATABASE taco_db;

USE taco_db;
CREATE TABLE tacos (
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    taco_name VARCHAR(255) NOT NULL,
    devoured BOOLEAN NOT NULL
);